### ISSUE TITLE
Based on openSUSE?

### ISSUE THREAD

**Issue by kellertk** [jostroOS/amogOS#11]
Might be a little more sus to base this on the [openSUSE](https://en.opensuse.org/HCL:Raspberry_Pi4) Pi port instead of Raspbian.

---
Opinions are my own and not of my employer.

**Comment by mobilegmYT** [comment]
> Might be a little more sus to base this on the [openSUSE](https://en.opensuse.org/HCL:Raspberry_Pi4) Pi port instead of Raspbian.
> 
> Opinions are my own and not of my employer.

I'll add it to the list, Might take a while though since I've never touched openSUS.

**Comment by BioHazard1282** [comment]
Maybe Ubuntu would be good too, since Raspbian is Debian, and Ubuntu is a derivative on Debian,

**Comment by buddyjojo** [comment]
Ubuntu is trash

**Comment by BioHazard1282** [comment]
Stock Ubuntu is, but Ubuntu MATE is very good.

**Comment by moon1789** [comment]
we only do lxde here , and ubuntu collects data so yeah :(

**Comment by moon1789** [comment]
> Might be a little more sus to base this on the [openSUSE](https://en.opensuse.org/HCL:Raspberry_Pi4) Pi port instead of Raspbian.
> 
> Opinions are my own and not of my employer.
s u s , we never touched opensuse

**Comment by MelihGMC2** [comment]
sussy baka

**Comment by mobilegmYT** [comment]
I have never even met a person who uses openSUS lol, might be best to stick for RPI OS rn.
Closing since it might happen, but it's too sus

**Comment by Dylstructor** [comment]
more like open sus 😳
