### ISSUE TITLE
Failure to boot on Raspberry Pi 400 and 3B

### ISSUE THREAD

**Issue by BioHazard1282** [jostroOS/amogOS#13]
So I understand this is based on Raspberry Pi OS, so I flashed this on a 16GB MicroSD card for maintenance. I flashed the .xz file with Raspberry Pi Imager, and when I boot this it just shows the blinking cursor for hours.

So I cut my losses and decided to reflash it and do the same thing on the Pi 3B, the same result.

Should I try using a different utility like Balena Etcher?

**Comment by mobilegmYT** [comment]
> So I understand this is based on Raspberry Pi OS, so I flashed this on a 16GB MicroSD card for maintenance. I flashed the .xz file with Raspberry Pi Imager, and when I boot this it just shows the blinking cursor for hours.
> 
> So I cut my losses and decided to reflash it and do the same thing on the Pi 3B, the same result.
> 
> Should I try using a different utility like Balena Etcher?

I recommend using https://github.com/Botspot/vdesktop to run the OS unless you plan on using amogos as your main OS.

**Comment by moon1789** [comment]
> So I understand this is based on Raspberry Pi OS, so I flashed this on a 16GB MicroSD card for maintenance. I flashed the .xz file with Raspberry Pi Imager, and when I boot this it just shows the blinking cursor for hours.
> 
> So I cut my losses and decided to reflash it and do the same thing on the Pi 3B, the same result.
> 
> Should I try using a different utility like Balena Etcher?

humm weird ,

**Comment by RickRollMaster101** [comment]
same :/

**Comment by mobilegmYT** [comment]
Will be fixed in 1.3.2 release, coming in like 1 hour.
