### ISSUE TITLE
More Sus

### ISSUE THREAD

**Issue by BlackObem** [jostroOS/amogOS#137]
Sussy Baka mode pls

**Comment by BlackObem** [comment]
I didn't read it, I’m really sorry, I couldn't contain myself.

Il giorno gio 28 apr 2022 alle 12:41 i am a car ***@***.***>
ha scritto:

**Comment by IAMACAR10** [comment]
ciao! i am sorry, i didn't mean to  sound rude. by any chance, are you italian?

**Comment by buddyjojo** [comment]
> it literaly says not to spam with sus issues for no reason

sus
