### ISSUE TITLE
Same problem: Failure to boot on 1.3.2

### ISSUE THREAD

**Issue by BioHazard1282** [jostroOS/amogOS#15]
Tried 1.3.2 on a Pi 400, still fails to boot. I don't see any errors, I can't pinpoint the cause.
On a 16GB MicroSD card, Raspberry Pi 400 with the latest EEPROM installed. Still hangs on the blinking cursor.

https://user-images.githubusercontent.com/44819642/121436206-62a37680-c93d-11eb-8fd6-7ca13f9e0a46.mov

**Comment by mobilegmYT** [comment]
Still have no idea what's causing it. You might just have better luck with using pi power tools to boot it as VM.

**Comment by harvey298** [comment]
similar problem on a Pi 3 Model B, it boots hangs on the cursor then restarts and enters a boot loop, can't chroot the system on my arch machine

**Comment by BioHazard1282** [comment]
> Still have no idea what's causing it. You might just have better luck with using pi power tools to boot it as VM.

That sucks, was looking forward to look at this cursed Operating System

**Comment by BioHazard1282** [comment]
I'll keep this issue open for others to see before downloading and using it

**Comment by BioHazard1282** [comment]
Tried doing this as a VM, fails to boot as well.
Could someone try using this on a Pi 4?

**Comment by hen6003** [comment]
I'm on a Pi 4 and same issue, sits on blank tty with a flashing cursor

**Comment by moon1789** [comment]
interesting...

**Comment by moon1789** [comment]
> I'm on a Pi 4 and same issue, sits on blank tty with a flashing cursor

https://github.com/jostroOS/amogOS/issues/15#issuecomment-860266129 humm

**Comment by BioHazard1282** [comment]
Some day this will be usuable on the Pi 400 :p

**Comment by Alvarito050506** [comment]
Hmm, might be a systemd issue, try adding `init=/bin/sh` to `cmdline.txt`... If it boots, it's most likely a systemd misconfiguration (or maybe not, but at least we know if the kernel boots :stuck_out_tongue:)

**Comment by mobilegmYT** [comment]
This is confirmed to be fixed in upcoming 1.4.0.

**Comment by Alvarito050506** [comment]
Nice, was it the partition thing?

**Comment by mobilegmYT** [comment]
> Nice, was it the partition thing?

Dunno, but ronr said it boots for him. I changed rc.local and used image-utils to gen the img.
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=313526&p=1879385#p1879020
