### ISSUE TITLE
dripping too hard not letting me stand too close

### ISSUE THREAD

**Issue by HelenaMKG** [jostroOS/amogOS#17]
cant use the os too much drip sussy amogus imposer red sus sussy 

please fix (sus)

**Comment by mobilegmYT** [comment]
What part is broken?

**Comment by sheepy0125** [comment]
hmm i don't think this is a real issue just saying

**Comment by sinisimattia** [comment]
no no it totally is, utterly unusable.
(amogOS gaming)

**Comment by mobilegmYT** [comment]
> no no it totally is, utterly unusable.
> (amogOS gaming)

Gaming with a ARM cpu and 256 mb of ram even in a VM is never usable :)
