### ISSUE TITLE
Possibility of making the project open-sourced and less sussy?

### ISSUE THREAD

**Issue by EimaMei** [jostroOS/amogOS#23]
I'd think it would be more beneficial to make this repo open-sourced and not the sussy closed-sourced. Here are the reasons:
1. Other developers will be able to review the code, while also fixing it. This makes the OS more stable for dripping activity.
2. It would make the project more transparent and less sussy. Not saying this OS does sussy stuff, but it wouldn't hurt to be transparent. 
3. Optimization. This ties in with reason 1. If the code is more efficiently rewritten, then it means it can run stuff better, such as among us.

**Comment by mobilegmYT** [comment]
> I'd think it would be more beneficial to make this repo open-sourced and not the sussy closed-sourced. Here are the reasons:
> 
> 1. Other developers will be able to review the code, while also fixing it. This makes the OS more stable for dripping activity.
> 2. It would make the project more transparent and less sussy. Not saying this OS does sussy stuff, but it wouldn't hurt to be transparent.
> 3. Optimization. This ties in with reason 1. If the code is more efficiently rewritten, then it means it can run stuff better, such as among us.

Read notes section in readme, the OS has no custom code, it uses other open source apps.

**Comment by ColleagueRiley** [comment]
source code when?

**Comment by mobilegmYT** [comment]
> source code when?

It does not have source code agagagagag
