### ISSUE TITLE
STILL a failure to boot.

### ISSUE THREAD

**Issue by BioHazard1282** [jostroOS/amogOS#27]
Same device (Raspberry Pi 400). Flashed with Balena Etcher and Raspberry Pi Imager on Ubuntu 20.10. Tried on 3 different storage devices, Samsung 16GB MicroSD card, SanDisk 32GB Ultra (Flash Drive), and an Dell 2TB Desktop Hard Drive and SSD.

None of these work. Am I doing something wrong or what? I'm dying to try this and this is starting to get old... older than my grandparents' age combined. 

It's said to work, but obviously this isn't.

**Comment by moon1789** [comment]
well , we are sorry for the issue , we exactly dont know what is causing that issue , i recommend trying out in vdesktop first . https://github.com/Botspot/vdesktop

**Comment by BioHazard1282** [comment]
> well , we are sorry for the issue , we exactly dont know what is causing that issue , i recommend trying out in vdesktop first . https://github.com/Botspot/vdesktop

Will this work in Ubuntu?

**Comment by mobilegmYT** [comment]
> > well , we are sorry for the issue , we exactly dont know what is causing that issue , i recommend trying out in vdesktop first . https://github.com/Botspot/vdesktop
> 
> Will this work in Ubuntu?

Ubuntu for raspberry pi? We've added a experimental x86 ISO to readme, I suggest running that in VM.

**Comment by mobilegmYT** [comment]
1.5 released, try that?

**Comment by moon1789** [comment]
t r y 1 . 5

**Comment by BioHazard1282** [comment]
![2021-07-12-134231_1680x1050_scrot](https://user-images.githubusercontent.com/44819642/125335718-1b2c5380-e30a-11eb-90a5-89f5a68fb080.png)

Works! Installed 1.5.0

**Comment by F-fengzi** [comment]
nice!

**Comment by mobilegmYT** [comment]
Fuck yeah! Now I'll need to remind myself how I packaged 1.5 for future versions since I forgot how I did it lol

**Comment by BioHazard1282** [comment]
However it does reboot once for some reason when you go on the desktop

**Comment by mobilegmYT** [comment]
> However it does reboot once for some reason when you go on the desktop
> 

I think that's intended, it runs some code on boot that fixes stuff which I ripped from rpi os

**Comment by BioHazard1282** [comment]
Ah I see

Also, I noticed you got Amogus on Wine. I have Exagear on Ubuntu 21.04, how'd ya do that?

**Comment by mobilegmYT** [comment]
Box86

**Comment by BioHazard1282** [comment]
Does it work with Wine wine-3.0-eltechs?

**Comment by mobilegmYT** [comment]
> Does it work with Wine wine-3.0-eltechs?

Im not a wine specialist so not sure what that is, but all I know is amogos has wine 5.21 with box86 and it uses some command line arguments to force unity to use gl instead of dx11 since pi can't run dx11
