### ISSUE TITLE
For issues regarding open source:

### ISSUE THREAD

**Issue by F-fengzi** [jostroOS/AmogOS#29]
From README: **AmogOS is not a custom OS, it's just riced RPi OS/Debian Buster. It doesn't have any custom-written source code.**

Linux is open sourced
Debian is open sourced
RPi OS is open sourced
And we're just modified RPi OS, there's no code written

_Never gonna give the Linux community up._

**Comment by mobilegmYT** [comment]
Should just slap some more stuff here.
amogOS uses these open source components:

__UI__
Openbox WM
LXDE for DE
xcompmgr for effects
Lightpad for the launchpad thing
xfce4-panel for dock and the panel

__Apps__
Just find a app and google it, its all open source

__Kernel/Drivers/Internal OS stuff__
All from RPi OS

__Wallpapers__
peekatchoo#0001 and yours truly

And that's basically all the open source software amogOS uses

**Comment by moon1789** [comment]
**If you ask me again for source code i am gonna report you to github**

**Comment by falseCloud** [comment]
amogus

**Comment by mobilegmYT** [comment]
"Too heated"

**Comment by mobilegmYT** [comment]
I think we can close since why is it even open

**Comment by F-fengzi** [comment]
~~no the close icon looks bad~~

**Comment by mobilegmYT** [comment]
stfu

**Comment by moon1789** [comment]
**AmogOS will never be based off OpenSUSe:tm:**

**Comment by moon1789** [comment]
Also **RTFM** before opening an issue.
