### ISSUE TITLE
its too sus

### ISSUE THREAD

**Issue by donnerkebab1730** [jostroOS/amogOS#3]
i think the os is a bit to sus

**Comment by F-fengzi** [comment]
Yes, thank you for reporting the issue
~~We're working on making this even more sus~~

**Comment by RaspberyPiProjectsandMore** [comment]
Interesting

**Comment by moon1789** [comment]
> Interesting

wa

**Comment by moon1789** [comment]
> i think the os is a bit to sus

sus 1.1 will be up in 5 min

**Comment by donnerkebab1730** [comment]
the susometer is of the charts

**Comment by robtech21** [comment]
> the susometer is of the charts

off*

**Comment by donnerkebab1730** [comment]
>:(

**Comment by 2231puppy** [comment]
why does this exist?

i love it

**Comment by mobilegmYT** [comment]
its so sus it isn't sus

**Comment by donnerkebab1730** [comment]
impossible.....

**Comment by 7man7LMYT** [comment]
how sussy can this get

**Comment by donnerkebab1730** [comment]
Imposter levels of sus

**Comment by Magallanesmapping321** [comment]
THE OS IS THE IMPOSTER

**Comment by donnerkebab1730** [comment]
mission acomplished closing issue now.

 imposter has been ejected
