### ISSUE TITLE
x86 version not booting, cannot find ldlinux.c32

### ISSUE THREAD

**Issue by GWTRC** [jostroOS/AmogOS#32]
Basically as the issue title states, the system just refuses to boot
![Screenshot from 2021-07-21 13-18-02](https://user-images.githubusercontent.com/37200805/126531496-2a3847e2-4b46-4af4-a5f8-5ee1f02a385e.png)
This screenshot is taken in Oracle VirtualBox, QEMU does the same thing

**Comment by mobilegmYT** [comment]
Hmmm this is a strange error, what VM software are you using?

**Comment by moon1789** [comment]
well umm , its my problem , this is a experimental beta x86 iso build so , e r r o r  s

**Comment by GWTRC** [comment]
> Hmmm this is a strange error, what VM software are you using?

I said in the original post, the screenshot is from VirtualBox, and QEMU throws the same errors

It's also worth reiterating I'm using the experimental x86 build

**Comment by mobilegmYT** [comment]
> > Hmmm this is a strange error, what VM software are you using?
> 
> I said in the original post, the screenshot is from VirtualBox, and QEMU throws the same errors
> 
> It's also worth reiterating I'm using the experimental x86 build

It is experimental for a reason. You could try downloading the virturalbox files directly  
https://drive.google.com/drive/folders/1w-glBtYI6VKJxNyVx0subedVbkMw4QJK

**Comment by GWTRC** [comment]
>It is experimental for a reason. You could try downloading the virturalbox files directly

Yes, I can very clearly see why it's experimental. I downloaded it expecting it not to work, but halting during the ISOLINUX part of the boot process is a pretty big problem is it not?

Thank you for the VBox file link, I'll give that a shot.

**Comment by mobilegmYT** [comment]
> Yes, I can very clearly see why it's experimental. I downloaded it expecting it not to work, but halting during the ISOLINUX part of the boot process is a pretty big problem is it not?

Currently, we use Linux live kit for the OS. Maybe I can try tweaking settings around for isolinux part.

**Comment by moon1789** [comment]
> > Yes, I can very clearly see why it's experimental. I downloaded it expecting it not to work, but halting during the ISOLINUX part of the boot process is a pretty big problem is it not?
> 
> Currently, we use Linux live kit for the OS. Maybe I can try tweaking settings around for isolinux part.

force our slave to make a better grub than the default one in linux live

**Comment by mobilegmYT** [comment]
Oh yea right remind me tmr to install among us grub

**Comment by moon1789** [comment]
ye i ma force our slave in  meantime

**Comment by mobilegmYT** [comment]
Seems like issue upstream with linux live kit. Will send issue, this will also delay x64 1.6

**Comment by mobilegmYT** [comment]
https://github.com/Tomas-M/linux-live/issues/149

**Comment by mobilegmYT** [comment]
Fixed and tested in new release, I think weird folder stuff happened.
