### ISSUE TITLE
ˢᵘˢ

### ISSUE THREAD

**Issue by Golde2341** [jostroOS/AmogOS#33]
░██████╗██╗░░░██╗░██████╗
██╔════╝██║░░░██║██╔════╝
╚█████╗░██║░░░██║╚█████╗░
░╚═══██╗██║░░░██║░╚═══██╗
██████╔╝╚██████╔╝██████╔╝
╚═════╝░░╚═════╝░╚═════╝░

**Comment by Golde2341** [comment]
sus

**Comment by F-fengzi** [comment]
oh no

**Comment by mobilegmYT** [comment]
. . .

**Comment by Golde2341** [comment]
░██████╗██╗░░░██╗░██████╗
██╔════╝██║░░░██║██╔════╝
╚█████╗░██║░░░██║╚█████╗░
░╚═══██╗██║░░░██║░╚═══██╗
██████╔╝╚██████╔╝██████╔╝
╚═════╝░░╚═════╝░╚═════╝░

**Comment by mobilegmYT** [comment]
Say since I just spent 2 hours making this, (shameless plug) would you be interested in some *sus* merch? https://merch.jostroos.ml/
