### ISSUE TITLE
Kernel...

### ISSUE THREAD

**Issue by Golde2341** [jostroOS/AmogOS#34]
What version of linux are made AMOG OS and kernel version or what distro are bassed?

**Comment by F-fengzi** [comment]
Raspberry Pi OS, or Debian Buster for x86 version

**Comment by mobilegmYT** [comment]
Kernel ver is latest one supplied in debian buster repos, not exactly sure about version but it's 4.19 or something afaik

**Comment by Golde2341** [comment]
it worked thx
