### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Golde2341** [jostroOS/AmogOS#35]
How can i install this master piece on a partition of my pc?

**Comment by mobilegmYT** [comment]
> How can i install this master piece on a partition of my pc?

We recommend using Universal USB Installer to install it onto a USB stick and boot it live. This will mean your changes won't be saved though. Hopefully the next update will have persistance.

**Comment by Golde2341** [comment]
> > How can i install this master piece on a partition of my pc?
> 
> We recommend using Universal USB Installer to install it onto a USB stick and boot it live. This will mean your changes won't be saved though. Hopefully the next update will have persistance.

but how can i install it intead use live version?

**Comment by mobilegmYT** [comment]
> > > How can i install this master piece on a partition of my pc?
> > 
> > 
> > We recommend using Universal USB Installer to install it onto a USB stick and boot it live. This will mean your changes won't be saved though. Hopefully the next update will have persistance.
> 
> but how can i install it intead use live version?

You can't, it's not added in yet

**Comment by Golde2341** [comment]
> > > > How can i install this master piece on a partition of my pc?
> > > 
> > > 
> > > We recommend using Universal USB Installer to install it onto a USB stick and boot it live. This will mean your changes won't be saved though. Hopefully the next update will have persistance.
> > 
> > 
> > but how can i install it intead use live version?
> 
> You can't, it's not added in yet

ok
