### ISSUE TITLE
GET OUT OF MY HEAD!!

### ISSUE THREAD

**Issue by osy86** [jostroOS/AmogOS#37]
# GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!GET OUT OF MY HEAD!!
![GET OUT OF MY HEAD!!](https://img.ifunny.co/images/9dcad2552781ebf5b98c278908485d33ea24eba6a91af064a911316db1dc5252_1.webp)

**Comment by moon1789** [comment]
> _**get out if issues**_

**Comment by F-fengzi** [comment]
It looks like you have catched the AMOGID-16 virus.

**Comment by moon1789** [comment]
> It looks like you have catched the AMOGID-16 virus.

time 4 painful amogid drug , totally not cocaine
