### ISSUE TITLE
imposter amon gus s

### ISSUE THREAD

**Issue by pigeonburger** [jostroOS/amogOS#4]
hello ,  ? is this amogus?? imposter??? hello is this the imposyer from amon gus?
sus!?

pleas halp me

**Comment by moon1789** [comment]
wat u s u s

**Comment by pigeonburger** [comment]
@moon1789 ![image](https://user-images.githubusercontent.com/70826123/120433701-ea7a0580-c3be-11eb-99b9-d5371193298b.png)

**Comment by moon1789** [comment]
w a

**Comment by moon1789** [comment]
kols isue

**Comment by Magallanesmapping321** [comment]
> @moon1789 ![image](https://user-images.githubusercontent.com/70826123/120433701-ea7a0580-c3be-11eb-99b9-d5371193298b.png)

![image](https://user-images.githubusercontent.com/83836512/120638053-a712ac00-c43d-11eb-96e6-6401c08f5235.png)

**Comment by Magallanesmapping321** [comment]
amogn yuis

**Comment by moon1789** [comment]
h
