### ISSUE TITLE
Custom GRUB Theme

### ISSUE THREAD

**Issue by GalacticCake** [jostroOS/AmogOS#42]
From my understanding you guys are using a Custom GRUB Theme from; 
https://github.com/sueperb/tasty-grubs/tree/main/themes/amogus
I think I saw your comment on reddit. 

Anyway, I saw the resolution of theme and realized it was too low of quality. I decided to recreate the image, and upscale it too 1920x1080. If you ever want to add this to your project feel free to. 

![testBG2](https://user-images.githubusercontent.com/72690766/131461922-086c4041-a5f9-483b-8ff0-9300e2183ccc.png)

Currently I'm working on the font, as the text is not in the proper location and the text is pixelated.

**Comment by moon1789** [comment]
Thanks :))

**Comment by F-fengzi** [comment]
👍

**Comment by F-fengzi** [comment]
OOPS accidently closed uh do you need to open again

**Comment by moon1789** [comment]
i do pro gaemr mov

**Comment by F-fengzi** [comment]
ues

**Comment by moon1789** [comment]
egish

**Comment by mobilegmYT** [comment]
Thanks so much! I'll add this to the todo list for next release

**Comment by moon1789** [comment]
oh frick

**Comment by mobilegmYT** [comment]
@GalacticCake you still working on the font thing?

**Comment by GalacticCake** [comment]
@mobilegmYT I'm not very good with customizing the GRUB settings, but I found an article that explains it. 
http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial

**Comment by mobilegmYT** [comment]
> @mobilegmYT I'm not very good with customizing the GRUB settings, but I found an article that explains it.
> http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial

I already have grub settings setup in amogos, but you said at the top of this issue: "Currently I'm working on the font, as the text is not in the proper location and the text is pixelated." Have you finished making a version with the unpixelized text?

**Comment by GalacticCake** [comment]
@mobilegmYT Nope. You can find a new font and use it, that one wasn't the best and was pixelated. I can't change it now because I'm on a new distribution

**Comment by mobilegmYT** [comment]
ah rip.
