### ISSUE TITLE
Custom Login Screen

### ISSUE THREAD

**Issue by GalacticCake** [jostroOS/AmogOS#43]
I got a friend of mine to create this custom Among Us Login Screen. I plan on using this for my Arch Linux...as soon as I figure out how to. 

![AU_Login_Design](https://user-images.githubusercontent.com/72690766/131532190-434d2960-b9cd-4adf-bd73-be5c0f3c197c.png)

The name of the user that you want to login is shown below or next to the knife. Depends on your preference, I'm going to put mine below the knife. 

![trash](https://user-images.githubusercontent.com/72690766/131532457-0cb838b8-5776-488d-9617-7eaa111d0fb5.png)
I made a rough drawing for my friend to reference when making this. It's really bad, but you're able to understand the point.

**Comment by mobilegmYT** [comment]
Interesting. One thing is that AmogOS is mostly a meme os, and alot of the code is hardcoded to the default user, so I don't think many people will be using the login prompt.

**Comment by GalacticCake** [comment]
> Interesting. One thing is that AmogOS is mostly a meme os, and alot of the code is hardcoded to the default user, so I don't think many people will be using the login prompt.

If you ever decide to add a login prompt, then this is always here. I'm trying to customize my Arch Linux more, so I will use this. Do you guys have an encryption option built into your Operating System? Also when you reboot your computer, you are met with a black screen. For me it's a terminal that I can not edit. It closes after a few seconds, but it still exists. I will add in a custom exit menu theme.

**Comment by mobilegmYT** [comment]
This is a meme OS lol, it doesn't need encryption

**Comment by GalacticCake** [comment]
> This is a meme OS lol, it doesn't need encryption

Yeah I thought it wouldn't have encryption. I still need one for mine so...
