### ISSUE TITLE
suse

### ISSUE THREAD

**Issue by buddyjojo** [jostroOS/AmogOS#45]
you guys should make it suse based because sus
also source code would be nice

**Comment by moon1789** [comment]
https://user-images.githubusercontent.com/72432771/132158889-392bea4e-5f34-489b-9d78-6ae4feb8e880.mp4

**Comment by buddyjojo** [comment]
I'll take that as a yes
i expect it by tomorrow

**Comment by moon1789** [comment]
OH FUCK NO

https://user-images.githubusercontent.com/72432771/132158972-d5bd93a8-c832-4681-89c1-500d62f2e357.mp4

**Comment by buddyjojo** [comment]
also where source code

**Comment by moon1789** [comment]
https://user-images.githubusercontent.com/72432771/132159249-bc7ce1e6-657c-4b59-871d-8448ef775302.mp4

**Comment by buddyjojo** [comment]
![image](https://user-images.githubusercontent.com/76966404/132159332-725c92fd-29e4-4b06-a96a-d9eed748379d.png)

**Comment by moon1789** [comment]
What source code i have my penguin army
https://user-images.githubusercontent.com/72432771/132159354-60542c6e-e139-4a5e-b4f8-f5cac68f539e.mp4

**Comment by buddyjojo** [comment]
your single penguin cant stop my fleet 
![image](https://user-images.githubusercontent.com/76966404/132159454-7f33bb73-7a77-4975-9664-7d56504089df.png)

**Comment by buddyjojo** [comment]
source, hand it over

**Comment by moon1789** [comment]
![image](https://user-images.githubusercontent.com/72432771/132159558-3f96c8de-929e-4e92-ae8b-fb0b91323f8f.png)

**Comment by buddyjojo** [comment]
so how's suse going

**Comment by buddyjojo** [comment]
you should be half way done by now

**Comment by moon1789** [comment]
don but n pakagin tolz

**Comment by buddyjojo** [comment]
well if it's done hand it over with source plz

**Comment by mobilegmYT** [comment]
we dont have source

**Comment by mobilegmYT** [comment]
read pinned issue

**Comment by buddyjojo** [comment]
nah nooz you just don't want to hand it out

**Comment by buddyjojo** [comment]
i know behind your lies

**Comment by mobilegmYT** [comment]
we dont have any custom apps

**Comment by buddyjojo** [comment]
stop trying to hide it

**Comment by buddyjojo** [comment]
gib source now

**Comment by mobilegmYT** [comment]
source for which exact component

**Comment by buddyjojo** [comment]
the os

**Comment by buddyjojo** [comment]
duh

**Comment by mobilegmYT** [comment]
which os component

**Comment by buddyjojo** [comment]
the entire thing

**Comment by buddyjojo** [comment]
all 69 gb of it

**Comment by mobilegmYT** [comment]
gosh

**Comment by buddyjojo** [comment]
oi stop trying to hide

**Comment by buddyjojo** [comment]
gib
now

**Comment by buddyjojo** [comment]
also suse

**Comment by mobilegmYT** [comment]
what do we have to hide if I put a bitcoin miner in it wouldn't it be obvious

**Comment by mobilegmYT** [comment]
there's only one btc miner in the os and the build containing it isn't even released yet

**Comment by buddyjojo** [comment]
yes you can hide one easily in the source

**Comment by mobilegmYT** [comment]
bro i dont even build it why would it have source code

**Comment by buddyjojo** [comment]
as the owner of the jostro project I demand suse and amogos source

**Comment by mobilegmYT** [comment]
suse doesnt even exist yet no ones working on it

**Comment by buddyjojo** [comment]
> bro i dont even build it why would it have source code

stop it with your lies

**Comment by buddyjojo** [comment]
> suse doesnt even exist yet no ones working on it

well then make it exist by tomorrow

**Comment by moon1789** [comment]
we lied , amogos has custom source code which was written by ms and apple employees and has a bitcoin miner inside.

**Comment by mobilegmYT** [comment]
~~but actually doe 1.4.0 and 1.6 both have money miner hidden inside because moon and I are starving~~

**Comment by moon1789** [comment]
~~true true~~

**Comment by buddyjojo** [comment]
~~why didn't you guys tell me~~

**Comment by mobilegmYT** [comment]
we are poor starving asian children, you are rich canadian

**Comment by buddyjojo** [comment]
i dont even have money

**Comment by buddyjojo** [comment]
my parents control it

**Comment by moon1789** [comment]
> my parents control it

we get like $1 every year as pocket money ONLY when we wash neighbours underwear everyday.

**Comment by F-fengzi** [comment]
hol up

**Comment by F-fengzi** [comment]
that's illegal

**Comment by moon1789** [comment]
:alwayshasbeen:

**Comment by F-fengzi** [comment]
hiding miners without notifying users is called malware, which is indeed illegal

**Comment by moon1789** [comment]
;-;-;

**Comment by joebobbio** [comment]
Reported to FBI, CIA, NSA, NASA, Jeff Bezos, Dr. Issac Kleiner, Elon Musk, and your mom.

**Comment by moon1789** [comment]
where putin and kim jong un

**Comment by F-fengzi** [comment]
omg you reported to my mom?

**Comment by joebobbio** [comment]
they are hacking your BTC wallet

**Comment by moon1789** [comment]
time to xavier mode

**Comment by F-fengzi** [comment]
her anger is gonna destroy fbi

**Comment by moon1789** [comment]
ha trolled phene

**Comment by buddyjojo** [comment]
so @moon1789 did ya finish suse

**Comment by moon1789** [comment]
pi went boom

**Comment by buddyjojo** [comment]
I'll go find you if it's not done

**Comment by moon1789** [comment]
https://www.google.com/maps/place/Sus+Hospital/@18.5545419,73.7475143,17z/data=!3m1!4b1!4m5!3m4!1s0x3bc2bfc9c97aec7f:0x7f42aa0cd5bc90fb!8m2!3d18.5545419!4d73.749703

**Comment by buddyjojo** [comment]
that's where you'll be soon if I don't see an suse build by 3 am

**Comment by moon1789** [comment]
OH SHIT OH FUCK

**Comment by buddyjojo** [comment]
you better get going :)

**Comment by joebobbio** [comment]
does amogos have a crypto miner in it

**Comment by buddyjojo** [comment]
honestly knowing nooz probably

**Comment by moon1789** [comment]
for some reason gnome has a crypto miner inside

**Comment by moon1789** [comment]
i looked up with dconf-editor

**Comment by joebobbio** [comment]
😟

**Comment by buddyjojo** [comment]
gnome sucks anyways

**Comment by moon1789** [comment]
https://user-images.githubusercontent.com/72432771/132279578-c37e1afd-cf2b-4c80-ad5f-96dcea5c889a.mp4

me when gnome

**Comment by Fluxxx222** [comment]
true

**Comment by AstrozTM** [comment]
true

**Comment by joebobbio** [comment]
False

**Comment by buddyjojo** [comment]
huh i forgot about this

**Comment by buddyjojo** [comment]
no suse so issue not closed

**Comment by moon1789** [comment]
*loads shotgun*

**Comment by buddyjojo** [comment]
oi your 14 days late

**Comment by buddyjojo** [comment]
you know what that means >:)

**Comment by moon1789** [comment]
So I'm getting 8 gb of ram so pls wait senpai

**Comment by buddyjojo** [comment]
i give you a day

**Comment by buddyjojo** [comment]
if you don't do it by tomorrow you'll be visiting the suspidal

**Comment by F-fengzi** [comment]
moon, don't listen to him
i'll kindly give you an extra minute
because i know that switching to openSUSe is hard, you're welcome.

**Comment by moon1789** [comment]
is it some sort of a personal attack?

**Comment by moon1789** [comment]
no one talks about this
