### ISSUE TITLE
[Feature] Pacstall for both versions of amogOS

### ISSUE THREAD

**Issue by Crewmategamingcoding** [jostroOS/AmogOS#46]
**Is your feature request related to a problem? Please describe.**
no way to easily install apps that's not on APT or pi-apps
**Describe the solution you'd like**
pacstall uses Arch linux's AUR and brings them to Debian/Ubuntu and it makes your life easier like you can install stuff like uwufetch without compiling it or to easily install the mc java launcher without opening pi apps

**Comment by mobilegmYT** [comment]
So it fetches stuff from official aur repos and does magic to install them in debian instead of arch?

**Comment by Crewmategamingcoding** [comment]
yeah

**Comment by mobilegmYT** [comment]
ill add it to the list

**Comment by Crewmategamingcoding** [comment]
:)

**Comment by mobilegmYT** [comment]
Closing since added
