### ISSUE TITLE
calamares installer is sus

### ISSUE THREAD

**Issue by Georg-prog-cmd** [jostroOS/AmogOS#48]
the calamares installer gave me Boost.Python error in job "unpackfs"

**Comment by mobilegmYT** [comment]
welp, then i just nuke calamares :)

send screenshot pls

**Comment by Georg-prog-cmd** [comment]
how do i install it on my pc without calamares?

**Comment by mobilegmYT** [comment]
> how do i install it on my pc without calamares?

Just don't 🤷 
Installing any os made by me into your pc is always a bad idea

**Comment by Georg-prog-cmd** [comment]
but i want to install it. My pc is so old i wanna install this on it

**Comment by mobilegmYT** [comment]
Hmm... what if, you boot amogos from USB, then copy amogos's manual installation files and follow them, but do the actions on your computers drive?

**Comment by Georg-prog-cmd** [comment]
manual installation files?

**Comment by mobilegmYT** [comment]
ye, read the instructions on https://github.com/jostroOS/AmogOS/blob/main/AmogOS-x64-installation-README.txt

**Comment by Georg-prog-cmd** [comment]
ok,now downloading zip

**Comment by MrVeink** [comment]
I'm having the same issue and here's a [screenshot](https://user-images.githubusercontent.com/59528135/132366947-015aac5c-88de-4515-81bc-e57d5c18630c.jpg).

**Comment by Georg-prog-cmd** [comment]
yeah i have the same

**Comment by mobilegmYT** [comment]
Yea, I'll just remove calmares next release and recommend you use manual install

**Comment by buddyjojo** [comment]
looks like the way you flash might cause this issue

**Comment by buddyjojo** [comment]
are you guys using rufus?

**Comment by DocdoZach** [comment]
sussy baka from impostor among us

**Comment by DocdoZach** [comment]
thats what im using

**Comment by buddyjojo** [comment]
dude come on this is serious
kinda

**Comment by DocdoZach** [comment]
but it has sus in the title

**Comment by buddyjojo** [comment]
eugh

**Comment by mobilegmYT** [comment]
> are you guys using rufus?

universal usb installer

**Comment by MrVeink** [comment]
> are you guys using rufus?
> 

It's running in a QEMU VM with KVM

**Comment by mobilegmYT** [comment]
> > are you guys using rufus?
> 
> It's running in a QEMU VM with KVM

Just use the vmdk image provided in release for vm

**Comment by MrVeink** [comment]
> > > are you guys using rufus?
> > 
> > It's running in a QEMU VM with KVM
> 
> Just use the vmdk image provided in release for vm

I'm guessing it's an already installed image. I want to have the installer.

**Comment by mobilegmYT** [comment]
> > > > are you guys using rufus?
> > > 
> > > 
> > > It's running in a QEMU VM with KVM
> > 
> > 
> > Just use the vmdk image provided in release for vm
> 
> I'm guessing it's an already installed image. I want to have the installer.

:( Do you know any good live USB os installers other than calamares then?

**Comment by Oshawott-kun** [comment]
guys how to install manual to disk without calamares installer
should I extract 01-core.sb\ ?

**Comment by Oshawott-kun** [comment]
> 
> 
> > > > > are you guys using rufus?
> > > > 
> > > > 
> > > > It's running in a QEMU VM with KVM
> > > 
> > > 
> > > Just use the vmdk image provided in release for vm
> > 
> > 
> > I'm guessing it's an already installed image. I want to have the installer.
> 
> :( Do you know any good live USB os installers other than calamares then?

Gnome Installer maybe?

**Comment by mobilegmYT** [comment]
> guys how to install manual to disk without calamares installer
> should I extract 01-core.sb\ to disk?

https://github.com/jostroOS/AmogOS/blob/main/AmogOS-x64-installation-README.txt

**Comment by mobilegmYT** [comment]
Calamares installer should be dropped in new release coming very soon, we'll try to find new working installer for future versions.
