### ISSUE TITLE
[Feature] AmogOS arm64?

### ISSUE THREAD

**Issue by artdeell** [jostroOS/AmogOS#49]
**Is your feature request related to a problem? Please describe.**
I wanna run arm64 stuff on my Pi 4 on chad AmogOS instead of bloatbuntu

**Describe the solution you'd like**
An arm64 version of AmogOS for RPi3/4

**Describe alternatives you've considered**
No alternatives for amogos

**Additional context**
...

**Comment by buddyjojo** [comment]
uh amogos started as a os for the pi4
i think the image is still somewhere here

**Comment by buddyjojo** [comment]
https://github.com/jostroOS/AmogOS/releases/tag/1.6.0

**Comment by mobilegmYT** [comment]
AmogOS already works on Pi4, but its 32-bit rn and no 64-bit version will exist until rpi foundation does stuff

**Comment by artdeell** [comment]
> AmogOS already works on Pi4, but its 32-bit rn and no 64-bit version will exist until rpi foundation does stuff

no amogus in box64 then sadly

**Comment by moon1789** [comment]
~~maybe we'll do a beta 64 bit Amogos from the beta rpi os 64 bit build who knows~~
