### ISSUE TITLE
Is Among Us in OS pirated?

### ISSUE THREAD

**Issue by papercore-dev** [jostroOS/AmogOS#51]
![image](https://user-images.githubusercontent.com/58584157/134351900-190f6375-1a60-477a-9eaf-75c28043af81.png)
This seems like legit Among Us copy because it is running in Wine and there is no bit-identical clone of Among Us. I want to ask - Is Among Us in this OS pirated or you recreated Among Us?

**Comment by moon1789** [comment]
pirated

**Comment by moon1789** [comment]
ok closing

**Comment by KSPAtlas** [comment]
> pirated

sus

**Comment by buddyjojo** [comment]
arrr we be pirates here

**Comment by Crewmategamingcoding** [comment]
but couldn't Innersloth take this down due to containing among us? couldn't you make a install script for it instead of a pirated version? or use the Android release on X86_64

**Comment by buddyjojo** [comment]
wellll technically we use a shared ea account from rpinews with bought among us
so its more of a issue with the ea eula

**Comment by buddyjojo** [comment]
so its technically not pirated

**Comment by mobilegmYT** [comment]
We're using a installer for newest build instead of piracy.
