### ISSUE TITLE
does the latest rpi release work on 32bit pcs?

### ISSUE THREAD

**Issue by MacOS-9** [jostroOS/AmogOS#53]
this question might be stupid but does the latest rpi release work on x86 based pcs? if yes then something is not working for me, if not then can there be a 32bit release?
if needed i can send the specs of my pc

**Comment by moon1789** [comment]
wait , use the x64?

**Comment by MacOS-9** [comment]
i thought you cant use 64bit operating systems on x86 based pcs

**Comment by moon1789** [comment]
wait
use the 64 bit  build for pcs
and 32 bit for pi's
