### ISSUE TITLE
[x64 bug]

### ISSUE THREAD

**Issue by Crewmategamingcoding** [jostroOS/AmogOS#55]
**Describe the bug**
calamares broken!!!!
**To Reproduce**
1. install amogOS
**Expected behavior**
install!!!

**Screenshots**

**Desktop (please complete the following information):**
 - Version 1.3.0
 - PC Specs
 intel core i5 2400
8GB RAM
Nvidia GEFORCE GTX 1050Ti
wifi card
**Additional context**
fix installer!!!!!!!!!!!! make it based on arch!!!!!!

**Comment by F-fengzi** [comment]
bruh moment
*moon dies*

**Comment by buddyjojo** [comment]
bruh lmao

**Comment by buddyjojo** [comment]
@mobilegmYT  you better fix it

**Comment by Crewmategamingcoding** [comment]
yez!!!!

**Comment by Crewmategamingcoding** [comment]
or I'm using xero linux!!!

**Comment by mobilegmYT** [comment]
im fixing it ok
