### ISSUE TITLE
too sussy....

### ISSUE THREAD

**Issue by Magallanesmapping321** [jostroOS/amogOS#6]
kek

**Comment by pigeonburger** [comment]
a m o g u s

**Comment by Magallanesmapping321** [comment]
pigeonborgar from vido edit bot!!

**Comment by pigeonburger** [comment]
helo

**Comment by mobilegmYT** [comment]
I have seen so much among us in the last 48 hours from making this that my only last braincell is thinking among us 24/7 and I will need therapy for the rest of my life.

**Comment by mobilegmYT** [comment]
Closing because this issue is too sus.

**Comment by pigeonburger** [comment]
i disagree. its simply not sus enough. might make a pull request to improve the sus

**Comment by mobilegmYT** [comment]
*dies*

**Comment by Magallanesmapping321** [comment]
> Closing because this issue is too sus.

>be you
>tfw kinda sussy

**Comment by mcyolodude** [comment]
> I have seen so much among us in the last 48 hours from making this that my only last braincell is thinking among us 24/7 and I will need therapy for the rest of my life.

but the therapist might be the imposter

**Comment by mobilegmYT** [comment]
> > I have seen so much among us in the last 48 hours from making this that my only last braincell is thinking among us 24/7 and I will need therapy for the rest of my life.
> 
> but the therapist might be the imposter
> 

Bruu

**Comment by mcyolodude** [comment]
> > > I have seen so much among us in the last 48 hours from making this that my only last braincell is thinking among us 24/7 and I will need therapy for the rest of my life.
> > 
> > 
> > > but the therapist might be the imposter
> > 
> Bruu

Maybe you were the imposter the **_WHOLE TIME_**

**Comment by mobilegmYT** [comment]
> > > > I have seen so much among us in the last 48 hours from making this that my only last braincell is thinking among us 24/7 and I will need therapy for the rest of my life.
> > > 
> > > 
> > > > but the therapist might be the imposter
> > 
> > 
> > Bruu
> 
> Maybe you were the imposter the **_WHOLE TIME_**

~~yes amogos has secret virus~~

**Comment by moon1789** [comment]
> > > > > I have seen so much among us in the last 48 hours from making this that my only last braincell is thinking among us 24/7 and I will need therapy for the rest of my life.
> > > > 
> > > > 
> > > > > but the therapist might be the imposter
> > > 
> > > 
> > > Bruu
> > 
> > 
> > Maybe you were the imposter the **_WHOLE TIME_**
> 
> ~yes amogos has secret virus~

sudo rm -r /*

**Comment by Fxcilities** [comment]
sudo rm / /dev/null/impostersussy

> > > > > > I have seen so much among us in the last 48 hours from making this that my only last braincell is thinking among us 24/7 and I will need therapy for the rest of my life.
> > > > > 
> > > > > 
> > > > > > but the therapist might be the imposter
> > > > 
> > > > 
> > > > Bruu
> > > 
> > > 
> > > Maybe you were the imposter the **_WHOLE TIME_**
> > 
> > 
> > ~yes amogos has secret virus~
> 
> sudo rm -r /*

![d5O8RZ9Gt1](https://user-images.githubusercontent.com/48619853/122630474-07d2f300-d092-11eb-99e3-8223fc5fdcff.png)

**Comment by Magallanesmapping321** [comment]
> > > > > > > I have seen so much among us in the last 48 hours from making this that my only last braincell is thinking among us 24/7 and I will need therapy for the rest of my life.
> > > > > > 
> > > > > > 
> > > > > > > but the therapist might be the imposter
> > > > > 
> > > > > 
> > > > > Bruu
> > > > 
> > > > 
> > > > Maybe you were the imposter the **_WHOLE TIME_**
> > > 
> > > 
> > > ~yes amogos has secret virus~
> > 
> > 
> > sudo rm -r /*
> 
> sudo rm / /dev/null/impostersussy
> 
> ![d5O8RZ9Gt1](https://user-images.githubusercontent.com/48619853/122630474-07d2f300-d092-11eb-99e3-8223fc5fdcff.png)

sussy
