### ISSUE TITLE
AmogOS-x64-installation-README.txt should be a .md 

### ISSUE THREAD

**Issue by buddyjojo** [jostroOS/AmogOS#60]
i would make this change myself but uh i don't know how to properly rename github files

**Comment by mobilegmYT** [comment]
Use git cli then

**Comment by mobilegmYT** [comment]
Also make sure all your changes are a PR so I can get free t-shirt

**Comment by buddyjojo** [comment]
pr?

**Comment by buddyjojo** [comment]
oh pull request

**Comment by buddyjojo** [comment]
shit i gotta make a branch now

**Comment by buddyjojo** [comment]
![image](https://user-images.githubusercontent.com/76966404/135734028-2f5fbdfe-87e0-4ca8-94dc-d09f8a67a4e1.png)

**Comment by buddyjojo** [comment]
it broke the ascii art

**Comment by buddyjojo** [comment]
looks like its just a problem with my pc so merging anyways
