### ISSUE TITLE
Wrong neofetch art

### ISSUE THREAD

**Issue by xslendix** [jostroOS/amogOS#7]

**Comment by moon1789** [comment]
w

**Comment by moon1789** [comment]
close issue

**Comment by xslendix** [comment]
lookat reddit post

**Comment by moon1789** [comment]
yes ik

**Comment by moon1789** [comment]
its the wrong neofetch , its the old version

**Comment by mobilegmYT** [comment]
> look at reddit post

I mean not that big of a issue and I'm too lazy to update the pictures.
